package review

import (
	"context"
	"fmt"

	"github.com/carlosboeing/crossrev/internal/core"
	"github.com/carlosboeing/crossrev/internal/intel"
	"github.com/carlosboeing/crossrev/internal/policy"
	"github.com/carlosboeing/crossrev/internal/prstate"
	"github.com/carlosboeing/crossrev/internal/ui"
)

// noChangesReason is the marker's reason for a pull request that changes no
// files. CrossRev writes it rather than a model, so `crossrev status` and
// every later reader get the same sentence on every run and every harness.
const noChangesReason = "the pull request's head is identical to its base, so it changes no files and there is nothing to review"

// Reasons for a pass whose changed files leave nothing to review, written by
// CrossRev rather than a model, so every run and every harness say the same
// thing.
const (
	// allMarkedReason: every changed path is marked linguist-generated in
	// the base tree's .gitattributes.
	allMarkedReason = "Every changed file is marked `linguist-generated` in `.gitattributes` at the base, so there was nothing to review. A PR that changes generated output without its source is worth a look."
	// allBacklogReason: every changed path is under the backlog destination.
	allBacklogReason = "Every changed file is under the backlog destination, so there was nothing to review."
	// allSkippedReason: every changed path was recognised as generated by a
	// built-in rule and fits no review prompt.
	allSkippedReason = "Every changed file was recognised as generated and is too large for one review prompt, so nothing was reviewed."
)

// nothingExcludedReason describes a pass emptied before packing: repository
// policy or the backlog rule removed every changed path.
func nothingExcludedReason(excluded []intel.Exclusion) string {
	backlog, marked := 0, 0
	for _, e := range excluded {
		if e.Reason == intel.GeneratedAttributeReason {
			marked++
		} else {
			backlog++
		}
	}
	switch {
	case backlog == 0:
		return allMarkedReason
	case marked == 0:
		return allBacklogReason
	default:
		return fmt.Sprintf("Nothing was reviewed: %s under the backlog destination, %s marked `linguist-generated` in `.gitattributes` at the base.", countFiles(backlog), countFiles(marked))
	}
}

// nothingSkippedReason describes a pass emptied during packing: policy
// removed some paths and every remaining one was recognised as generated and
// oversized. When both sources emptied the set, the reason names both
// counts.
func nothingSkippedReason(policyExcluded, skipped int) string {
	if policyExcluded == 0 {
		return allSkippedReason
	}
	return fmt.Sprintf("Nothing was reviewed: %s excluded by repository policy, %s recognised as generated and too large for one review prompt.", countFiles(policyExcluded), countFiles(skipped))
}

func countFiles(n int) string {
	if n == 1 {
		return "1 changed file"
	}
	return fmt.Sprintf("%d changed files", n)
}

// finishNothingToReviewRun settles a pass whose changed files leave nothing
// to review — every path excluded by repository policy before packing, or
// every remaining path skipped as oversized generated output. No harness is
// invoked: the answer is CrossRev's to give rather than a model's.
//
// The pass records blocked, the existing terminal state for a pass that
// could not do its work, and takes the halted label. It never records
// converged: policy.Converged refuses a required count of zero
// (internal/policy/convergence.go:50), and a green label on a pull request
// nothing read is the failure the coverage engine exists to prevent.
func (l *Leg) finishNothingToReviewRun(ctx context.Context, req Request, loaded Context, pass int, claimID int64, marker prstate.Marker, reason string, out *Result) (Result, publishState) {
	marker.Verdict = prstate.Some(string(core.VerdictBlocked))
	marker.BlockedReason = prstate.Some(reason)
	marker.DoneTS = prstate.Some(l.now().Unix())
	marker.Unanchored = prstate.Some(0)
	marker.State = core.PassComplete

	minFix := loaded.Config.Get(".policy.min_fix_severity")
	if minFix == "" {
		minFix = string(core.SeverityMedium)
	}
	summary := SummaryBody(nil, marker, RenderContext{
		Repo:    loaded.Repo.String(),
		PR:      req.PR,
		MinFix:  minFix,
		MaxPass: atoi(loaded.Config.Get(".policy.max_passes_per_cycle")),
	})

	// ui_say: the state, before the comment lands, so a failure below still
	// leaves the operator knowing why the leg stopped.
	out.Messages = append(out.Messages, ui.Say(fmt.Sprintf(
		"%s#%d leaves nothing to review — stopping without calling a reviewer", loaded.Repo, req.PR)))

	written, err := l.editClaim(ctx, loaded.Repo, claimID, summary, marker, coverageOverflow(loaded))
	if err != nil {
		out.Outcome = OutcomeError
		out.Err = err
		out.Marker = marker
		return *out, publishState{}
	}
	out.Marker = written
	// The record is durable from here, so nothing below may rewrite it.
	state := publishState{settled: true}
	out.Messages = append(out.Messages, ui.OK("posted a summary comment"))

	warns, err := l.applyPassLabels(ctx, req, loaded, pass, policy.PassHalted)
	out.Messages = append(out.Messages, warns...)
	if err != nil {
		out.Outcome = OutcomeError
		out.Err = err
		return *out, state
	}

	out.Outcome = OutcomeHalted
	out.Reason = reason
	return *out, state
}

// finishNoChangesRun settles a pass whose pull request changes no files. No
// harness is invoked: there is nothing to send and nothing to account for,
// so the answer is CrossRev's to give rather than a model's.
//
// This is the case where git and GitHub agree. A disagreement — git
// enumerating nothing while the API still reports a count, which a lagging
// read after a force-push or a revert produces — is not settled here,
// because the diff comes from the forge rather than from git and may hold
// real content worth reviewing. That pass runs, and Run binds its coverage
// obligation before it does, so it can report findings but can never report
// green.
//
// The pass records blocked, the existing terminal state for a pass that
// could not do its work. It never records converged: policy.Converged
// refuses a required count of zero (internal/policy/convergence.go:50), and
// a green label on a pull request nothing read is the failure the coverage
// engine exists to prevent.
func (l *Leg) finishNoChangesRun(ctx context.Context, req Request, loaded Context, ad admission, cap int, claimID int64, marker prstate.Marker, out *Result) (Result, publishState) {
	marker.Verdict = prstate.Some(string(core.VerdictBlocked))
	marker.BlockedReason = prstate.Some(noChangesReason)
	marker.DoneTS = prstate.Some(l.now().Unix())
	marker.Unanchored = prstate.Some(0)
	marker.State = core.PassComplete

	minFix := loaded.Config.Get(".policy.min_fix_severity")
	if minFix == "" {
		minFix = string(core.SeverityMedium)
	}
	summary := SummaryBody(nil, marker, RenderContext{
		Repo:      loaded.Repo.String(),
		PR:        req.PR,
		MinFix:    minFix,
		MaxPass:   cap,
		NoChanges: true,
		BaseRef:   loaded.PR.BaseRefName,
		HeadRef:   loaded.PR.HeadRefName,
	})

	// ui_say: the state, before the comment lands, so a failure below still
	// leaves the operator knowing why the leg stopped.
	out.Messages = append(out.Messages, ui.Say(fmt.Sprintf(
		"%s#%d changes no files — stopping without calling a reviewer", loaded.Repo, req.PR)))

	written, err := l.editClaim(ctx, loaded.Repo, claimID, summary, marker, coverageOverflow(loaded))
	if err != nil {
		out.Outcome = OutcomeError
		out.Err = err
		out.Marker = marker
		return *out, publishState{}
	}
	out.Marker = written
	// The record is durable from here, so nothing below may rewrite it.
	state := publishState{settled: true}
	// ui_ok (lib/run.sh:1299).
	out.Messages = append(out.Messages, ui.OK("posted a summary comment"))

	warns, err := l.applyPassLabels(ctx, req, loaded, ad.pass, policy.PassHalted)
	out.Messages = append(out.Messages, warns...)
	if err != nil {
		out.Outcome = OutcomeError
		out.Err = err
		return *out, state
	}

	out.Outcome = OutcomeHalted
	out.Reason = noChangesReason
	return *out, state
}
