// descriptor.go — the credential half of lib/harnesses.json, compiled in.
//
// lib/harnesses.sh is "the harness descriptor, and the only thing that reads
// it" (lib/harnesses.sh:2). Everything credential-shaped that the Bash side
// asks it for goes through harness_get (lib/harnesses.sh:131), which answers
// `jq -r '… // empty'` — so a JSON null and an absent key both come back as the
// empty string. The Go reads keep that: a null `secret` is "", a null
// `staging.env` is "", and an unknown harness name is a zero Credential rather
// than an error, because cred_assert_present, cred_prepare and cred_assert_fresh
// all fall through quietly on one.
//
// The file under assets/ is generated by scripts/sync-embedded-assets.sh
// because a `go:embed` pattern is package-relative and cannot contain `..`.
// Never edit it: lib/harnesses.json is canonical, the script copies it, and both
// `--check` and TestEmbeddedDescriptorIsTheCanonicalFile fail on drift.

package cred

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"slices"
	"strings"
	"sync"
)

//go:embed assets/harnesses.json
var harnessDescriptor []byte

// DescriptorJSON is lib/harnesses.json, byte for byte.
//
// It hands back a copy each time for the reason internal/validate's accessors
// do: an exported `var x []byte` is writable from any package in the binary,
// and these bytes decide which environment variables a model-facing process
// keeps.
func DescriptorJSON() []byte { return bytes.Clone(harnessDescriptor) }

// Staging is `.credential.staging` — where a restored credential is written and
// which environment variable points the harness at it.
type Staging struct {
	// Kind is one of none, file, home or env, the set lib/harnesses.sh:59
	// validates against.
	Kind string `json:"kind"`
	// Env is the variable Prepare exports, empty when the descriptor says null.
	Env string `json:"env"`
	// Path is the file inside the scratch directory: relative, non-empty, and
	// never containing a `..` segment. Load refuses a descriptor that breaks
	// that, and Prepare refuses the path again at the write.
	//
	// It is empty only for a harness whose descriptor writes null, which is
	// every harness that stages nothing.
	Path string `json:"path"`

	// pathDeclared separates `"path": null` from `"path": ""`. The shell's
	// validator skips the first and refuses the second
	// (lib/harnesses.sh:71-73), and both decode into the same empty string.
	pathDeclared bool
}

// UnmarshalJSON exists for pathDeclared and nothing else.
func (s *Staging) UnmarshalJSON(raw []byte) error {
	var wire struct {
		Kind string  `json:"kind"`
		Env  string  `json:"env"`
		Path *string `json:"path"`
	}
	if err := json.Unmarshal(raw, &wire); err != nil {
		return err
	}
	s.Kind, s.Env, s.Path, s.pathDeclared = wire.Kind, wire.Env, "", wire.Path != nil
	if wire.Path != nil {
		s.Path = *wire.Path
	}
	return nil
}

// relativePath is the `relative` filter lib/harnesses.sh:31-33 defines: a
// non-empty string that does not start at the root and carries no `..` segment.
//
// A leading slash is refused for parity rather than for reach — filepath.Join
// folds one, so an absolute staging path stays inside the scratch home. `..`
// is the segment that leaves it.
func relativePath(path string) bool {
	if path == "" || strings.HasPrefix(path, "/") {
		return false
	}
	return !slices.Contains(strings.Split(path, "/"), "..")
}

// Credential is one harness's `.credential` block.
//
// Only the fields this package reads are declared. A key the descriptor carries
// and nothing here needs — `store`, `provenance`, `access_token_seconds` — is
// left out rather than parsed and ignored, because a field nobody reads is a
// field nobody notices going stale.
type Credential struct {
	// Archetype is A, B or C. preflight_pairing_supported reads it
	// (lib/preflight.sh:222-228); nothing in this package does, and it is here
	// so a caller deciding a pairing does not need a second descriptor reader.
	Archetype string `json:"archetype"`
	// Billing is subscription, api or unknown.
	Billing string `json:"billing"`
	// Secret is the environment variable a hosted runner delivers the
	// credential in, empty when the harness needs none.
	Secret string `json:"secret"`
	// EnvNames is every variable this harness's credential can arrive in. The
	// union across all harnesses is what StripFor subtracts a keep list from.
	EnvNames []string `json:"env_names"`
	// EnvKeep is what this harness may still hold once it is running.
	EnvKeep []string `json:"env_keep"`
	// SeedHint is the sentence a refusal ends with, naming how to re-seed.
	SeedHint string `json:"seed_hint"`
	// Staging is where a restored credential goes.
	Staging Staging `json:"staging"`
	// AccessTokenPath is the path to the access token inside the stored
	// credential, as the descriptor writes it: `.tokens.access_token`, or null
	// for a store that holds no JWT.
	//
	// The JSON key still says jq, because the descriptor is shared with the
	// Bash side and renaming it would be a change to a file both read. The Go
	// name does not, because this build has no jq and refuses anything jq could
	// express that a dotted object path cannot — a field called AccessTokenJQ
	// promises a program it will not run.
	AccessTokenPath string `json:"access_token_jq"`
	// AssertFresh is whether an expiry can be read out of this store at all.
	// An archetype-A store holds none, and demanding one would stop exactly the
	// harnesses that cannot answer it (lib/credentials.sh:205-210).
	AssertFresh bool `json:"assert_fresh"`
	// Refresher is whether this credential rotates and needs the single-writer
	// refresher workflow.
	Refresher bool `json:"refresher"`
}

// Descriptor is one harness's name with its credential block.
type Descriptor struct {
	// Harness is the descriptor's own name for it, empty for a name the
	// descriptor does not carry.
	Harness string
	// Credential is the block, zero-valued for an unknown harness.
	Credential Credential
}

// Known reports that the descriptor carries this harness.
func (d Descriptor) Known() bool { return d.Harness != "" }

// Document is every harness's credential block, in the order lib/harnesses.json
// declares them.
type Document struct {
	entries []Descriptor
	index   map[string]int
	// vendorNames is the sorted union of every env_names entry, which is jq's
	// `[ .harnesses[].credential.env_names[]? ] | unique` at
	// lib/credentials.sh:182. Computed once at load because StripFor answers it
	// for every leg.
	vendorNames []string
}

// ErrDescriptor is returned for a descriptor that cannot be read.
//
// The Bash loader validates twelve things and dies on the first
// (lib/harnesses.sh:29-88); it does that because the descriptor names sourced
// paths, install commands and quarantine paths handed to `rm -rf`. None of that
// is this package's business, so the checks here are only the ones that decide
// whether the credential reads below mean anything: it parses, it carries a
// non-empty `harnesses` array, and every entry has a name that appears once.
var ErrDescriptor = fmt.Errorf("the harness descriptor cannot be read")

// Load parses a harness descriptor.
func Load(raw []byte) (Document, error) {
	var doc struct {
		Harnesses []struct {
			Name       string     `json:"name"`
			Credential Credential `json:"credential"`
		} `json:"harnesses"`
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	if err := decoder.Decode(&doc); err != nil {
		return Document{}, fmt.Errorf("%w: %w", ErrDescriptor, err)
	}
	if len(doc.Harnesses) == 0 {
		return Document{}, fmt.Errorf("%w: it names no harnesses", ErrDescriptor)
	}

	loaded := Document{
		entries: make([]Descriptor, 0, len(doc.Harnesses)),
		index:   make(map[string]int, len(doc.Harnesses)),
	}
	var vendor []string
	for _, entry := range doc.Harnesses {
		if entry.Name == "" {
			return Document{}, fmt.Errorf("%w: a harness entry carries no name", ErrDescriptor)
		}
		if _, duplicate := loaded.index[entry.Name]; duplicate {
			return Document{}, fmt.Errorf("%w: harness name %q appears more than once", ErrDescriptor, entry.Name)
		}
		staging := entry.Credential.Staging
		if staging.pathDeclared && !relativePath(staging.Path) {
			return Document{}, fmt.Errorf("%w: the staging path %q for %s is absolute, empty, or contains a .. segment",
				ErrDescriptor, staging.Path, entry.Name)
		}
		loaded.index[entry.Name] = len(loaded.entries)
		loaded.entries = append(loaded.entries, Descriptor{Harness: entry.Name, Credential: entry.Credential})
		vendor = append(vendor, entry.Credential.EnvNames...)
	}

	// jq's `unique` sorts and deduplicates, and the strip set inherits that
	// order (lib/credentials.sh:182-184). The parity vectors in
	// tests/fixtures/parity/credentials.json are recorded in it.
	slices.Sort(vendor)
	loaded.vendorNames = slices.Compact(vendor)
	return loaded, nil
}

var (
	embedded     Document
	embeddedErr  error
	embeddedOnce sync.Once
)

// Descriptors is the compiled-in descriptor, parsed once.
//
// It returns an error rather than panicking because the bytes are generated:
// scripts/sync-embedded-assets.sh copies lib/harnesses.json in, and a copy that
// went in malformed should stop the command that needed it with a message
// rather than the whole process at init time.
func Descriptors() (Document, error) {
	embeddedOnce.Do(func() {
		embedded, embeddedErr = Load(harnessDescriptor)
	})
	return embedded, embeddedErr
}

// For answers the descriptor for a harness, or a zero Descriptor for a name it
// does not carry.
//
// An unknown name is not an error, which is harness_get's own answer: it prints
// nothing, so cred_assert_present returns at its `secret` check, cred_prepare
// stages nothing, and cred_assert_fresh returns 0 because
// `.credential.assert_fresh` is not the string "true"
// (lib/credentials.sh:126, :143, :213).
func (d Document) For(harness string) Descriptor {
	if at, found := d.index[harness]; found {
		return d.entries[at]
	}
	return Descriptor{}
}

// Names lists the harnesses in descriptor order.
func (d Document) Names() []string {
	names := make([]string, 0, len(d.entries))
	for _, entry := range d.entries {
		names = append(names, entry.Harness)
	}
	return names
}

// VendorNames is the sorted union of every harness's env_names.
func (d Document) VendorNames() []string { return slices.Clone(d.vendorNames) }
