package cred_test

import (
	"errors"
	"os"
	"slices"
	"testing"

	"github.com/carlosboeing/crossrev/internal/cred"
)

// descriptors is the compiled-in document, or a fatal test failure.
func descriptors(t *testing.T) cred.Document {
	t.Helper()
	doc, err := cred.Descriptors()
	if err != nil {
		t.Fatalf("reading the embedded descriptor: %v", err)
	}
	return doc
}

// The embedded copy is what a compiled binary reads, so it has to be the file a
// contributor edits. `go:embed` cannot reach it directly, because its patterns
// are package-relative and cannot contain `..`; the copy under assets/ is
// generated by scripts/sync-embedded-assets.sh, and this is the half of the
// drift check that runs inside `go test`.
func TestEmbeddedDescriptorIsTheCanonicalFile(t *testing.T) {
	canonical, err := os.ReadFile("../../lib/harnesses.json")
	if err != nil {
		t.Fatalf("reading lib/harnesses.json: %v", err)
	}
	if string(cred.DescriptorJSON()) != string(canonical) {
		t.Error("the embedded descriptor differs from lib/harnesses.json — run scripts/sync-embedded-assets.sh")
	}
}

// The descriptor decides which environment variables a model-facing process
// keeps, and an exported slice variable is writable from any package in the
// binary. The accessor answers a copy.
func TestTheEmbeddedDescriptorCannotBeWrittenThrough(t *testing.T) {
	got := cred.DescriptorJSON()
	if len(got) == 0 {
		t.Fatal("the embedded descriptor is empty")
	}
	want := got[0]
	got[0] = 'X'
	if cred.DescriptorJSON()[0] != want {
		t.Error("writing through the accessor's result changed the embedded copy")
	}
}

// harness_get answers `jq -r '… // empty'` (lib/harnesses.sh:131), so a JSON
// null reads back as the empty string. Three fields in the shipped descriptor
// are null for at least one harness, and each one drives a branch: a null
// `secret` skips the missing-secret refusal, a null `staging.env` stages
// nothing, and a null `access_token_jq` means there is no expiry to read.
func TestANullDescriptorFieldReadsAsEmpty(t *testing.T) {
	doc := descriptors(t)

	agy := doc.For("agy")
	if !agy.Known() {
		t.Fatal("the descriptor carries no agy")
	}
	if agy.Credential.Secret != "" {
		t.Errorf("agy secret = %q, want empty: the descriptor says null", agy.Credential.Secret)
	}
	if agy.Credential.Staging.Env != "" {
		t.Errorf("agy staging env = %q, want empty", agy.Credential.Staging.Env)
	}

	claude := doc.For("claude")
	if claude.Credential.AccessTokenPath != "" {
		t.Errorf("claude access token path = %q, want empty", claude.Credential.AccessTokenPath)
	}
	if claude.Credential.AssertFresh {
		t.Error("claude is marked assert_fresh; its setup token carries no expiry to read")
	}
}

// An unknown harness is not an error. harness_get prints nothing for one, so
// cred_assert_present returns at its secret check, cred_prepare stages nothing,
// and cred_assert_fresh returns 0 (lib/credentials.sh:126, :143, :213). Every
// one of those depends on a zero Credential rather than a failure.
func TestAnUnknownHarnessIsAZeroDescriptor(t *testing.T) {
	got := descriptors(t).For("not-a-harness")
	if got.Known() {
		t.Error("an unknown harness reports itself as known")
	}
	if got.Harness != "" || got.Credential.Secret != "" || got.Credential.AssertFresh {
		t.Errorf("an unknown harness is not zero-valued: %+v", got)
	}
}

// The five, in the order lib/harnesses.json declares them. internal/core states
// the same order at internal/core/harness.go:15-21, and a strip set's order
// depends on this document having been read whole.
func TestTheDescriptorCarriesTheFiveHarnessesInOrder(t *testing.T) {
	want := []string{"claude", "codex", "agy", "grok", "opencode"}
	if got := descriptors(t).Names(); !slices.Equal(got, want) {
		t.Errorf("names = %v, want %v", got, want)
	}
}

// jq's `unique` sorts, and the strip set inherits that order
// (lib/credentials.sh:182).
func TestTheVendorNamesAreSortedAndDeduplicated(t *testing.T) {
	got := descriptors(t).VendorNames()
	want := []string{
		"ANTHROPIC_API_KEY",
		"CLAUDE_CODE_OAUTH_TOKEN",
		"CROSSREV_CODEX_AUTH",
		"CROSSREV_GROK_AUTH",
		"CROSSREV_OPENCODE_AUTH",
	}
	if !slices.Equal(got, want) {
		t.Errorf("vendor names = %v, want %v", got, want)
	}
}

// VendorNames answers a copy, for the same reason DescriptorJSON does: this
// list is the input to every strip set in the binary.
func TestVendorNamesCannotBeWrittenThrough(t *testing.T) {
	doc := descriptors(t)
	got := doc.VendorNames()
	got[0] = "OVERWRITTEN"
	if doc.VendorNames()[0] == "OVERWRITTEN" {
		t.Error("writing through VendorNames changed the document")
	}
}

// Load checks only what decides whether the credential reads mean anything.
// The Bash loader's other checks exist because the descriptor names sourced
// paths and quarantine paths handed to `rm -rf` (lib/harnesses.sh:5-8), and
// none of that is this package's business.
func TestLoadRefusesADescriptorItCannotReasonAbout(t *testing.T) {
	for _, tc := range []struct {
		name string
		raw  string
	}{
		{"not JSON at all", "{"},
		{"no harnesses key", `{"version":1}`},
		{"an empty harnesses array", `{"version":1,"harnesses":[]}`},
		{"an entry with no name", `{"harnesses":[{"credential":{}}]}`},
		{"a duplicated name", `{"harnesses":[{"name":"a"},{"name":"a"}]}`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := cred.Load([]byte(tc.raw)); !errors.Is(err, cred.ErrDescriptor) {
				t.Errorf("Load(%s) error = %v, want ErrDescriptor", tc.raw, err)
			}
		})
	}
}

// A duplicate name is refused rather than resolved, because jq keeps the last
// of two duplicate object keys and discards the first silently
// (lib/harnesses.sh:11-15). A reader that picked one would have picked it in
// silence.
func TestLoadAcceptsTheShippedDescriptor(t *testing.T) {
	doc, err := cred.Load(cred.DescriptorJSON())
	if err != nil {
		t.Fatalf("Load on the shipped descriptor: %v", err)
	}
	if len(doc.Names()) != 5 {
		t.Errorf("names = %v, want five harnesses", doc.Names())
	}
}
