package initcmd_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/carlosboeing/crossrev/internal/initcmd"
)

// repoRoot is where the canonical templates live, relative to this package.
const repoRoot = "../.."

// templateDir is the one directory lib/init.sh renders from, as
// "$ROOT/templates/" (lib/init.sh:570, lib/init.sh:894).
const templateDir = "templates"

// embedded pairs each canonical file under templates/ with the accessor that
// hands back its compiled-in copy. Both tests below read it, so a template with
// no accessor and an accessor pointing at the wrong file are each one failure.
var embedded = []struct {
	file string
	read func() []byte
}{
	{file: "crossrev.yml", read: initcmd.PolicyTemplate},
	{file: "crossrev-review.yml", read: initcmd.ReviewWorkflowTemplate},
	{file: "crossrev-resolve.yml", read: initcmd.ResolveWorkflowTemplate},
	{file: "crossrev-watchdog.yml", read: initcmd.WatchdogWorkflowTemplate},
	{file: "crossrev-token-refresh.yml", read: initcmd.TokenRefreshWorkflowTemplate},
	{file: "operator-config.yml", read: initcmd.OperatorConfigTemplate},
}

// The copies under assets/ are generated by scripts/sync-embedded-assets.sh,
// and a hand edit to one changes what a binary writes into a repository while
// the file a contributor edits stays as it was. `--check` catches that in lint;
// this catches it in the suite, so a Go run alone is enough to see it.
func TestEmbeddedAssetsAreTheCanonicalFiles(t *testing.T) {
	for _, tt := range embedded {
		t.Run(tt.file, func(t *testing.T) {
			canonical := filepath.Join(repoRoot, templateDir, tt.file)
			want, err := os.ReadFile(canonical)
			if err != nil {
				t.Fatalf("reading %s: %v", canonical, err)
			}
			if !bytes.Equal(tt.read(), want) {
				t.Errorf("the embedded copy differs from %s/%s; run: bash scripts/sync-embedded-assets.sh", templateDir, tt.file)
			}
		})
	}
}

// A template added to templates/ with no accessor here is a file `init` can
// write from a checkout and not from a binary. The list above is checked
// against the directory rather than trusted, because nothing else would notice.
func TestEveryTemplateHasAnAccessor(t *testing.T) {
	entries, err := os.ReadDir(filepath.Join(repoRoot, templateDir))
	if err != nil {
		t.Fatalf("reading %s: %v", templateDir, err)
	}
	covered := make(map[string]bool, len(embedded))
	for _, e := range embedded {
		covered[e.file] = true
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !covered[entry.Name()] {
			t.Errorf("%s/%s is not embedded; add an accessor and a pair in scripts/sync-embedded-assets.sh", templateDir, entry.Name())
		}
	}
	if len(entries) == 0 {
		t.Fatalf("%s is empty, so this test proves nothing", templateDir)
	}
}

// An accessor that handed back its own array would let any package in the
// binary edit what every later caller writes into a repository.
func TestEmbeddedAssetsAreCopies(t *testing.T) {
	for _, tt := range embedded {
		t.Run(tt.file, func(t *testing.T) {
			first := tt.read()
			if len(first) == 0 {
				t.Fatal("the embedded file is empty")
			}
			first[0] = 'x'
			if second := tt.read(); second[0] == 'x' {
				t.Error("the accessor hands out its own array, so a caller can edit what every later caller reads")
			}
		})
	}
}
