// assets.go — the workflow and config templates `init` writes, compiled in.
//
// A checkout renders these from the tree it was installed from: the workflow
// loop reads "$ROOT/templates/crossrev-$t.yml" (lib/init.sh:570) and the policy
// file is yq'd out of "$ROOT/templates/crossrev.yml" (lib/init.sh:874).
// templates/operator-config.yml is the local-mode config an operator copies by
// hand (docs/installation.md:114). A binary has no checkout, so it carries the
// bytes.
//
// The files under assets/templates/ are generated by
// scripts/sync-embedded-assets.sh because a `go:embed` pattern is
// package-relative and cannot contain `..`. Never edit one: the files under
// templates/ at the repository root are canonical, the script copies them, and
// both `--check` and assets_test.go fail on drift.
//
// Rendering is not here. This file hands back the template bytes; the
// substitutions lib/init.sh makes on the way out belong to the step that ports
// _init_render_workflow and _init_write_config.

package initcmd

import "embed"

// One glob rather than six paths, so a template added to templates/ and synced
// is carried by the binary rather than silently left behind. Nothing else would
// notice: an accessor is what a caller reaches for, and a file with no accessor
// is caught by assets_test.go instead.
//
//go:embed assets/templates/*
var templates embed.FS

// template reads one embedded copy.
//
// A name the embedded tree does not carry is a mistake in this file, not
// something a caller can cause, and it is fixed by a recompile — so it panics
// rather than growing an error return every call site would have to ignore.
// TestEveryTemplateHasAnAccessor is what makes sure the six names below and the
// files under templates/ stay the same set.
//
// embed.FS hands back a fresh slice per call, so an accessor's result is the
// caller's to edit; TestEmbeddedAssetsAreCopies pins that.
func template(name string) []byte {
	b, err := templates.ReadFile("assets/templates/" + name)
	if err != nil {
		panic("initcmd: embedded template: " + err.Error())
	}
	return b
}

// PolicyTemplate is templates/crossrev.yml, byte for byte.
func PolicyTemplate() []byte { return template("crossrev.yml") }

// ReviewWorkflowTemplate is templates/crossrev-review.yml, byte for byte.
func ReviewWorkflowTemplate() []byte { return template("crossrev-review.yml") }

// ResolveWorkflowTemplate is templates/crossrev-resolve.yml, byte for byte.
func ResolveWorkflowTemplate() []byte { return template("crossrev-resolve.yml") }

// WatchdogWorkflowTemplate is templates/crossrev-watchdog.yml, byte for byte.
func WatchdogWorkflowTemplate() []byte { return template("crossrev-watchdog.yml") }

// TokenRefreshWorkflowTemplate is templates/crossrev-token-refresh.yml, byte
// for byte. init writes it only for a pairing that needs a refresher
// (lib/init.sh:149-150).
func TokenRefreshWorkflowTemplate() []byte { return template("crossrev-token-refresh.yml") }

// OperatorConfigTemplate is templates/operator-config.yml, byte for byte.
func OperatorConfigTemplate() []byte { return template("operator-config.yml") }
