// assets.go — the two JSON schemas, compiled in.
//
// Every shipped harness is given the schema for the leg it is running, and all
// but one constrain their own output to it (lib/run.sh:1149-1150, 2070-2071). A checkout
// passes the file under `schemas/`; a binary has no checkout to pass, so it
// carries the bytes.
//
// The files under assets/ are generated by scripts/sync-embedded-assets.sh
// because a `go:embed` pattern is package-relative and cannot contain `..`.
// Never edit one: `schemas/findings.schema.json` and
// `schemas/resolve.schema.json` are canonical, the script copies them, and both
// `--check` and TestEmbeddedSchemasAreTheCanonicalFiles fail on drift.
//
// The schemas are shipped as bytes rather than parsed here on purpose. This
// package does not validate against them — lib/validate.sh explains why, and
// findings.go and resolve.go carry the flat checks that stand in.

package validate

import _ "embed"

// FindingsSchema is schemas/findings.schema.json, byte for byte.
//
//go:embed assets/findings.schema.json
var FindingsSchema []byte

// ResolveSchema is schemas/resolve.schema.json, byte for byte.
//
//go:embed assets/resolve.schema.json
var ResolveSchema []byte
