// assets.go — the two JSON schemas, compiled in.
//
// Every shipped harness is given the schema for the leg it is running, and all
// but one constrain their own output to it (lib/run.sh:1149-1150, 2070-2071). A checkout
// passes the file under `schemas/`; a binary has no checkout to pass, so it
// carries the bytes.
//
// The files under assets/ are generated by scripts/sync-embedded-assets.sh
// because a `go:embed` pattern is package-relative and cannot contain `..`.
// Never edit one: `schemas/findings.schema.json` and
// `schemas/resolve.schema.json` are canonical, the script copies them, and both
// `--check` and TestEmbeddedSchemasAreTheCanonicalFiles fail on drift.
//
// The schemas are shipped as bytes rather than parsed here on purpose. This
// package does not validate against them — lib/validate.sh explains why, and
// findings.go and resolve.go carry the flat checks that stand in.

package validate

import (
	"bytes"
	_ "embed"
)

// The two are unexported, and the accessors below hand back a copy each time.
// An exported `var x []byte` is writable from any package, and these bytes are
// what constrains a model's output — one assignment anywhere in the binary
// widens the schema for every later leg, with nothing to report it.

//go:embed assets/findings.schema.json
var findingsSchema []byte

//go:embed assets/resolve.schema.json
var resolveSchema []byte

// FindingsSchema is schemas/findings.schema.json, byte for byte.
func FindingsSchema() []byte { return bytes.Clone(findingsSchema) }

// ResolveSchema is schemas/resolve.schema.json, byte for byte.
func ResolveSchema() []byte { return bytes.Clone(resolveSchema) }
