package validate_test

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/carlosboeing/crossrev/internal/validate"
)

// The embedded copies are what a compiled binary hands a harness, so they have
// to be the files a contributor edits. `go:embed` cannot reach them directly,
// because its patterns are package-relative and cannot contain `..`; the copies
// under assets/ are generated by scripts/sync-embedded-assets.sh, and this is
// the half of the drift check that runs inside `go test`.
func TestEmbeddedSchemasAreTheCanonicalFiles(t *testing.T) {
	for _, tc := range []struct {
		name     string
		embedded []byte
		path     string
	}{
		{"findings", validate.FindingsSchema(), "../../schemas/findings.schema.json"},
		{"resolve", validate.ResolveSchema(), "../../schemas/resolve.schema.json"},
	} {
		canonical, err := os.ReadFile(tc.path)
		if err != nil {
			t.Fatalf("reading %s: %v", tc.path, err)
		}
		if string(tc.embedded) != string(canonical) {
			t.Errorf("%s: the embedded copy differs from %s — run scripts/sync-embedded-assets.sh",
				tc.name, tc.path)
		}
	}
}

// Claude Code's --json-schema refuses a schema naming the 2020-12 meta-schema
// with "no schema with key or ref", before the model is ever called
// (tests/test-schemas.sh:24-30). Asserted on the embedded copy as well, because
// that is the one a binary sends.
func TestEmbeddedSchemasCarryNoMetaSchemaKey(t *testing.T) {
	for _, tc := range []struct {
		name string
		raw  []byte
	}{
		{"findings", validate.FindingsSchema()},
		{"resolve", validate.ResolveSchema()},
	} {
		var doc map[string]json.RawMessage
		if err := json.Unmarshal(tc.raw, &doc); err != nil {
			t.Fatalf("%s: the embedded copy is not JSON: %v", tc.name, err)
		}
		for _, key := range []string{"$schema", "$id"} {
			if _, present := doc[key]; present {
				t.Errorf("%s: carries %s, which Claude Code cannot resolve", tc.name, key)
			}
		}
	}
}

// The schemas constrain a model's output, and an exported `var x []byte` is
// writable from any package in the binary. The accessors answer a copy, so a
// caller writing through one is not widening the schema for every later leg.
func TestTheEmbeddedSchemasCannotBeWrittenThrough(t *testing.T) {
	for _, tc := range []struct {
		name string
		read func() []byte
	}{
		{"findings", validate.FindingsSchema},
		{"resolve", validate.ResolveSchema},
	} {
		got := tc.read()
		if len(got) == 0 {
			t.Fatalf("%s is empty", tc.name)
		}
		want := got[0]
		got[0] = 'X'
		if tc.read()[0] != want {
			t.Errorf("%s: writing through the accessor's result changed the embedded copy",
				tc.name)
		}
	}
}
