package cli

import (
	"bytes"
	"os"
	"testing"
)

// canonicalVersion is the file bin/crossrev:64 reads: `$ROOT/VERSION`, where
// ROOT is the checkout the shell was invoked from (bin/crossrev:26).
const canonicalVersion = "../../VERSION"

// The copy under assets/ is generated by scripts/sync-embedded-assets.sh. A
// hand edit changes what `crossrev version` prints while the file every release
// step reads stays as it was — and the release check in scripts/lint.sh
// compares VERSION against package.json, not against this.
//
// The comparison is the raw bytes, before Version deletes whitespace, because
// the generated copy is a copy and not a rendering.
func TestEmbeddedVersionIsTheCanonicalFile(t *testing.T) {
	want, err := os.ReadFile(canonicalVersion)
	if err != nil {
		t.Fatalf("reading %s: %v", canonicalVersion, err)
	}
	if len(want) == 0 {
		t.Fatalf("%s is empty, so this test proves nothing", canonicalVersion)
	}
	if !bytes.Equal([]byte(embeddedVersion), want) {
		t.Errorf("the embedded copy differs from VERSION; run: bash scripts/sync-embedded-assets.sh")
	}
}

// installedVersion is what compose hands Version, and a build that carried no
// version at all would print a blank line rather than refuse. This is the check
// that the seam is filled: it fails if installedVersion goes back to "".
func TestInstalledVersionIsTheEmbeddedFile(t *testing.T) {
	if installedVersion() == "" {
		t.Fatal("installedVersion answers nothing, so `crossrev version` refuses in every build")
	}
	if installedVersion() != embeddedVersion {
		t.Errorf("installedVersion = %q, want the embedded file %q", installedVersion(), embeddedVersion)
	}
}
