// assets.go — the version `crossrev version` prints, compiled in.
//
// A checkout reads it off disk: bin/crossrev:26 sets ROOT to the checkout it
// was invoked from and :64 does `cat "$ROOT/VERSION"`. A binary has no
// checkout, so it carries the bytes.
//
// assets/VERSION is generated by scripts/sync-embedded-assets.sh because a
// `go:embed` pattern is package-relative and cannot contain `..`. Never edit
// it: VERSION at the repository root is canonical — scripts/lint.sh compares
// it against package.json and the release workflow verifies the tag against
// it — and both `--check` and assets_test.go fail on drift.

package cli

import _ "embed"

// embeddedVersion is VERSION at the repository root, byte for byte, trailing
// newline and all. Version deletes the whitespace on the way out, the way
// `tr -d '[:space:]'` does at bin/crossrev:64, so the copy stays a copy.
//
//go:embed assets/VERSION
var embeddedVersion string
