package resolve

import (
	"context"
	"encoding/json"
	"strings"
	"testing"

	"github.com/carlosboeing/crossrev/internal/core"
	"github.com/carlosboeing/crossrev/internal/intel"
	"github.com/carlosboeing/crossrev/internal/prstate"
	"github.com/carlosboeing/crossrev/internal/prstate/storetest"
)

// The resolve leg rewrites the review comment. A current generation's skip
// and its linguist-generated exclusion have to survive that rewrite, and a
// header skip quotes the marker from the committed head blob.
func TestResolveKeepsTheSkipWarningWhenItRewritesTheReviewComment(t *testing.T) {
	e := setup(t)
	e.addReview(t, defaultFindings(), "issues-remain")
	e.adapter.payloads = []json.RawMessage{oneFindingPayload()}

	const skipPath = "src/webAssets.ts"
	const excludedPath = "dist/bundle.js"
	markerLine := "// Code generated by scripts/build-embed.mjs. DO NOT EDIT."
	blob := []byte(markerLine + "\nexport const assets = {}\n")
	e.git.show = map[string][]byte{skipPath: blob}

	size := 350797
	gen := prstate.Generation{
		Gen:      1,
		Revision: core.RevisionPair{Base: e.base, Head: e.head},
		Engine:   core.FileEngineVersion,
		Slot:     prstate.DefaultSlot,
		Producer: prstate.Producer{Harness: "codex"},
		Form:     prstate.GenerationFull,
		Paths:    []string{"app.ts"},
		Records: []prstate.Record{{
			Type:       prstate.CoverageRecordUnit,
			UnitID:     string(core.FileUnitID("app.ts")),
			PathIndex:  0,
			Kind:       prstate.CoverageGranularityFile,
			Change:     string(core.ChangeModified),
			BodyDigest: core.BodyDigestHex([]byte("app.ts")),
			Verdict:    prstate.Some("no_issue"),
		}},
		Excluded: []prstate.CoverageExclusion{
			{Path: skipPath, Reason: intel.SkipReason(intel.FileUnit{Generated: intel.SignalHeader, Body: make([]byte, size)})},
			{Path: excludedPath, Reason: intel.GeneratedAttributeReason},
		},
		ScopeReport: prstate.ScopeReport{ExaminedScope: "read the batch"},
	}
	store := storetest.NewFakeStore()
	e.forge.ledger = store
	handle, err := store.PublishGeneration(context.Background(),
		prstate.SlotRef{Repo: e.slug, Number: 42, Slot: prstate.DefaultSlot}, prstate.Handle{}, gen)
	if err != nil {
		t.Fatalf("PublishGeneration: %v", err)
	}
	setReviewCoverage(t, e, handle)

	got := e.run(t)
	if got.Err != nil {
		t.Fatalf("Run: %v", got.Err)
	}
	var body string
	for _, edit := range e.forge.edits {
		if edit.CommentID == 9001 {
			body = edit.Body
		}
	}
	if body == "" {
		t.Fatal("the review comment was not edited")
	}
	excerpt := intel.HeaderExcerpt(blob)
	if excerpt == "" || excerpt != markerLine {
		t.Fatalf("HeaderExcerpt = %q, want the marker line", excerpt)
	}
	for _, want := range []string{
		"> **Warning: 1 changed file was not reviewed.**",
		"- `src/webAssets.ts` — generated (header: `" + excerpt + "`), 350,797 bytes, over the 184,320-byte budget.",
		"Excluded by repository policy: `dist/bundle.js` — not reviewed.",
		"Reviewed 1 of 3 changed files at `aaaaaaa`. 1 was not reviewed; see the warning above.",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("edited review comment is missing %q\n--- comment ---\n%s", want, body)
		}
	}
	var readHead bool
	for _, call := range e.git.showCalls {
		if call.Path == skipPath && call.Revision.SHA() == e.head.SHA() {
			readHead = true
		}
	}
	if !readHead {
		t.Errorf("Show was not called for %s at the head", skipPath)
	}
}
