// assets.go — the harness descriptor and the price extract, compiled in.
//
// lib/harnesses.sh:2 calls itself "the harness descriptor, and the only thing
// that reads it", and lib/usage.sh:15 says pricing "reads the committed extract
// at lib/prices.json and nothing else". A checkout hands both files to jq by
// path (lib/harnesses.sh:19-22, lib/usage.sh:22-25); a binary has no checkout,
// so it carries the bytes.
//
// The files under assets/ are generated by scripts/sync-embedded-assets.sh
// because a `go:embed` pattern is package-relative and cannot contain `..`.
// Never edit one: lib/harnesses.json and lib/prices.json are canonical, the
// script copies them, and both `--check` and the tests below fail on drift.
//
// # Two packages embed the descriptor, and that is deliberate
//
// internal/cred/assets/harnesses.json holds the same bytes. The alternative was
// for this package to call cred.DescriptorJSON, which would make the credential
// package the descriptor's owner — the opposite of the Bash arrangement, where
// lib/credentials.sh asks lib/harnesses.sh. Neither copy can drift: both are
// generated from lib/harnesses.json by the same script, and `--check` compares
// each against it rather than against the other.

package harness

import (
	"bytes"
	_ "embed"
)

//go:embed assets/harnesses.json
var harnessDescriptor []byte

//go:embed assets/prices.json
var priceExtract []byte

// DescriptorJSON is lib/harnesses.json, byte for byte.
//
// It hands back a copy each time for the reason internal/validate's accessors
// do: an exported `var x []byte` is writable from any package in the binary,
// and these bytes name install commands, environment variables and the
// quarantine paths handed to a move.
func DescriptorJSON() []byte { return bytes.Clone(harnessDescriptor) }

// PricesJSON is lib/prices.json, byte for byte, cloned for the same reason.
func PricesJSON() []byte { return bytes.Clone(priceExtract) }
