package harness_test

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/carlosboeing/crossrev/internal/cred"
	"github.com/carlosboeing/crossrev/internal/harness"
)

// repoRoot is where the canonical files live, relative to this package.
const repoRoot = "../.."

// The embedded copies are generated by scripts/sync-embedded-assets.sh, and a
// hand edit to one changes what a binary reads while the file a contributor
// edits stays as it was. `--check` catches that in lint; this catches it in the
// suite, so a Go run alone is enough to see it.
func TestEmbeddedAssetsAreTheCanonicalFiles(t *testing.T) {
	for _, tt := range []struct {
		name      string
		canonical string
		embedded  []byte
	}{
		{name: "the harness descriptor", canonical: "lib/harnesses.json", embedded: harness.DescriptorJSON()},
		{name: "the price extract", canonical: "lib/prices.json", embedded: harness.PricesJSON()},
	} {
		t.Run(tt.name, func(t *testing.T) {
			want, err := os.ReadFile(filepath.Join(repoRoot, tt.canonical))
			if err != nil {
				t.Fatalf("reading %s: %v", tt.canonical, err)
			}
			if !bytes.Equal(tt.embedded, want) {
				t.Errorf("the embedded copy differs from %s; run: bash scripts/sync-embedded-assets.sh", tt.canonical)
			}
		})
	}
}

// The descriptor is embedded twice — here and in internal/cred — and the two
// copies are generated from one canonical file. Nothing else compares them, so
// a sync script that lost one entry would leave the two packages reading
// different bytes with both `--check` runs green.
func TestTheTwoEmbeddedDescriptorsAgree(t *testing.T) {
	if !bytes.Equal(harness.DescriptorJSON(), cred.DescriptorJSON()) {
		t.Error("internal/harness and internal/cred carry different descriptor bytes")
	}
}

// An accessor that handed back its own array would let any package in the
// binary edit what every later caller reads.
func TestEmbeddedAssetsAreCopies(t *testing.T) {
	for _, tt := range []struct {
		name string
		read func() []byte
	}{
		{name: "DescriptorJSON", read: harness.DescriptorJSON},
		{name: "PricesJSON", read: harness.PricesJSON},
	} {
		t.Run(tt.name, func(t *testing.T) {
			first := tt.read()
			if len(first) == 0 {
				t.Fatal("the embedded file is empty")
			}
			first[0] = 'x'
			if second := tt.read(); second[0] == 'x' {
				t.Error("the accessor hands out its own array, so a caller can edit what every later caller reads")
			}
		})
	}
}

// The embedded bytes have to parse, or every command that needs them fails at
// the point of use rather than here.
func TestEmbeddedAssetsParse(t *testing.T) {
	if !json.Valid(harness.DescriptorJSON()) {
		t.Error("the embedded descriptor is not valid JSON")
	}
	if !json.Valid(harness.PricesJSON()) {
		t.Error("the embedded price extract is not valid JSON")
	}
	if _, err := harness.Descriptors(); err != nil {
		t.Errorf("the embedded descriptor does not load: %v", err)
	}
	if _, err := harness.PriceTable(); err != nil {
		t.Errorf("the embedded price extract does not load: %v", err)
	}
}
