// Code generated by internal/testgen/policy; DO NOT EDIT.

package prstate_test

type stateParityCase struct {
	desc    string
	markers string
	want    int
}

var parityStatePassCases = []stateParityCase{
	{desc: "no trusted marker means pass 1", markers: "[]", want: 1},
	{desc: "one completed review means pass 2", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"}]", want: 2},
	{desc: "the resolve leg does not advance the pass number", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"},{\"leg\":\"resolve\",\"pass\":1,\"state\":\"complete\"}]", want: 2},
	{desc: "a declined pass does not advance the pass number", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"},{\"leg\":\"review\",\"pass\":2,\"state\":\"declined\"}]", want: 2},
}

var parityStateMaxPassCases = []stateParityCase{
	{desc: "no markers means max pass 0", markers: "[]", want: 0},
	{desc: "one completed review means max pass 1", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"}]", want: 1},
	{desc: "a declined pass counts for max pass", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"},{\"leg\":\"review\",\"pass\":2,\"state\":\"declined\"}]", want: 2},
}

var parityStateCurrentReviewPassCases = []stateParityCase{
	{desc: "no markers means current review pass 0", markers: "[]", want: 0},
	{desc: "one completed review means current review pass 1", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"}]", want: 1},
	{desc: "the resolve leg does not advance current review pass", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"},{\"leg\":\"resolve\",\"pass\":1,\"state\":\"complete\"}]", want: 1},
	{desc: "a declined review pass is not current review pass", markers: "[{\"leg\":\"review\",\"pass\":1,\"state\":\"complete\"},{\"leg\":\"review\",\"pass\":2,\"state\":\"declined\"}]", want: 1},
}
