// assets.go — the two skill files, compiled in.
//
// ADR 0007 has the orchestrator reproducing both skill texts into every prompt
// rather than leaving them to harness discovery. Two reasons, both concrete: the
// quarantine moves `.claude/` and `.agents/` out of the checkout before any
// invocation, which is exactly where a workflow would have planted the skills;
// and reproducing the text makes the protocol byte-identical across harnesses,
// which is the property that lets pass 2 judge pass 1.
//
// A checkout reads them from `skills/`. A binary carries them, so editing the
// rubric needs a build and shipping it needs a release. The property ADR 0007
// protects is unchanged — the rubric and the orchestrator still ship at one
// revision — and the frozen prompt fixtures catch a rubric edit that changes
// prompt bytes unintentionally.
//
// The files under assets/ are generated by scripts/sync-embedded-assets.sh
// because a `go:embed` pattern is package-relative and cannot contain `..`.
// Never edit one: `skills/pr-review/SKILL.md` and `skills/pr-resolve/SKILL.md`
// are canonical, the script copies them, and both `--check` and
// TestEmbeddedSkillsAreTheCanonicalFiles fail on drift.

package prompt

import (
	"bytes"
	_ "embed"
)

// The two are unexported, and the accessors below hand back a copy each time.
// An exported `var x []byte` is writable from any package, and the whole rubric
// is what a leg is judged against — one assignment anywhere in the binary
// changes what every later prompt reproduces, with nothing to report it. A copy
// costs one allocation per prompt and removes process-wide mutable state.

//go:embed assets/pr-review.SKILL.md
var reviewSkill []byte

//go:embed assets/pr-resolve.SKILL.md
var resolveSkill []byte

// ReviewSkill is skills/pr-review/SKILL.md, byte for byte.
func ReviewSkill() []byte { return bytes.Clone(reviewSkill) }

// ResolveSkill is skills/pr-resolve/SKILL.md, byte for byte.
func ResolveSkill() []byte { return bytes.Clone(resolveSkill) }
