package prompt_test

import (
	"os"
	"testing"
)

// readFile is the canonical file at the repository root, read so an embedded
// copy can be compared against it. `go:embed` cannot reach it directly, because
// its patterns are package-relative and cannot contain `..`; the copies under
// assets/ are generated by scripts/sync-embedded-assets.sh, and this comparison
// is the half of the drift check that runs inside `go test`.
func readFile(t *testing.T, path string) []byte {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return b
}
