// assets.go — the two skill files, compiled in.
//
// ADR 0007 has the orchestrator reproducing both skill texts into every prompt
// rather than leaving them to harness discovery. Two reasons, both concrete: the
// quarantine moves `.claude/` and `.agents/` out of the checkout before any
// invocation, which is exactly where a workflow would have planted the skills;
// and reproducing the text makes the protocol byte-identical across harnesses,
// which is the property that lets pass 2 judge pass 1.
//
// A checkout reads them from `skills/`. A binary carries them, so editing the
// rubric needs a build and shipping it needs a release. The property ADR 0007
// protects is unchanged — the rubric and the orchestrator still ship at one
// revision — and the frozen prompt fixtures catch a rubric edit that changes
// prompt bytes unintentionally.
//
// The files under assets/ are generated by scripts/sync-embedded-assets.sh
// because a `go:embed` pattern is package-relative and cannot contain `..`.
// Never edit one: `skills/pr-review/SKILL.md` and `skills/pr-resolve/SKILL.md`
// are canonical, the script copies them, and both `--check` and
// TestEmbeddedSkillsAreTheCanonicalFiles fail on drift.

package prompt

import _ "embed"

// ReviewSkill is skills/pr-review/SKILL.md, byte for byte.
//
//go:embed assets/pr-review.SKILL.md
var ReviewSkill []byte

// ResolveSkill is skills/pr-resolve/SKILL.md, byte for byte.
//
//go:embed assets/pr-resolve.SKILL.md
var ResolveSkill []byte
