#!/usr/bin/env bash
#
# Render generated harness documentation tables from assets/harnesses.json.
#
# Usage:
#   scripts/render-harness-docs.sh         # rewrite files in place
#   scripts/render-harness-docs.sh --check # fail if any file would change
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DESC="$REPO_ROOT/assets/harnesses.json"

check_mode=0
if [[ "${1:-}" == "--check" ]]; then
  check_mode=1
fi

if [[ ! -f "$DESC" ]]; then
  printf 'render-harness-docs: %s not found\n' "$DESC" >&2
  exit 1
fi

render_readme() {
  jq -r '
def lifetime_str:
  if . == 31536000 then "1 year"
  elif . == 864000 then "10 days"
  elif . == 21600 then "6 hours"
  elif . == 3360 then "56 minutes"
  elif . == 900 then "15 minutes"
  elif . == null then "—"
  else (. / 60 | tostring) + " minutes" end;

def cred_store_str:
  if .credential then
    if .credential.archetype == "A" then "`\(.credential.seed_command)`, purpose-built"
    elif .credential.archetype == "B" then "OAuth access token in \(.credential.store)"
    elif .credential.archetype == "C" then .credential.store
    else .credential.store end
  else "OAuth access token" end;

def survives_str:
  if .credential then
    if .credential.archetype == "A" then "Yes"
    elif .credential.archetype == "B" and .credential.refresher then "Yes, with the refresher below"
    elif .credential.archetype == "C" and .credential.provenance == "measured" and (.credential.secret // "") != "" then "Yes, by self-refreshing"
    elif .credential.archetype == "C" then "No, CrossRev cannot seed into a hosted runner yet"
    else "No" end
  else "No" end;

"| Harness | Subscription credential | Lifetime | Survives an ephemeral runner |",
"|---|---|---|---|",
([.harnesses[], (.not_driven[] | select(.archetype != null))] | .[] |
  "| `\(.name)` | \(cred_store_str) | \((.credential.access_token_seconds // .access_token_seconds) | lifetime_str) | \(survives_str) |"
)
' "$DESC"
}

render_credentials() {
  jq -r '
def lifetime_str:
  if . == 31536000 then "1 year"
  elif . == 864000 then "10 days"
  elif . == 21600 then "6 hours"
  elif . == 3360 then "56 minutes"
  elif . == 900 then "15 minutes"
  elif . == null then "—"
  else (. / 60 | tostring) + " minutes" end;

def cred_store_str:
  if .credential then
    if .credential.archetype == "A" then "`\(.credential.seed_command)`, purpose-built"
    elif .credential.archetype == "B" then "OAuth access token in \(.credential.store)"
    elif .credential.archetype == "C" then .credential.store
    else .credential.store end
  else "OAuth access token" end;

def hosted_str:
  if .credential then
    if .credential.archetype == "A" then "Works directly"
    elif .credential.archetype == "B" and .credential.refresher then "Works, with the refresher below"
    elif .credential.archetype == "C" and .credential.provenance == "measured" and (.credential.secret // "") != "" then "Works, by self-refreshing"
    elif .credential.archetype == "C" then "Use a self-hosted runner"
    else "Use a self-hosted runner" end
  elif .archetype == "B" then "Use a self-hosted runner, or a static endpoint token"
  else "No" end;

"| Harness | Subscription credential | Access-token lifetime | On a hosted runner |",
"|---|---|---|---|",
([.harnesses[], (.not_driven[] | select(.archetype != null))] | .[] |
  "| `\(.name)` | \(cred_store_str) | \((.credential.access_token_seconds // .access_token_seconds) | lifetime_str) | \(hosted_str) |"
)
' "$DESC"
}

render_architecture() {
  jq -r '
.endpoint_host as $ep |
def notes_str:
  (if .schema_style == "inline" then "Takes the schema **inline** as a JSON string."
   elif .schema_style == "path" and (.sandbox_args | length > 0) then "Takes the schema as a **file path**."
   elif .schema_style == "prompt" then "No schema flag: the schema travels inside the prompt, and CrossRev extracts the JSON from the answer text itself."
   else "" end) +
  (if .name == $ep then " Also the path to any Anthropic-compatible endpoint" else "" end) +
  (if (.sandbox_args | length > 0) then " Runs with `\((.sandbox_args | join(" ")))`" else "" end) +
  (if (.legs // ["review","resolve"]) == ["review"] then " Review-only" else "" end);

"| Adapter | Harness | Notes |",
"|---|---|---|",
([.harnesses[]] | .[] |
  "| `\(.name)` | \(.product_name) |" + (if notes_str == "" then "" else " " + notes_str end) + " |"
)
' "$DESC"
}

replace_table() {
  local target="$1" content_file="$2"
  awk -v content_file="$content_file" '
    BEGIN { in_block = 0 }
    /<!-- crossrev:harness-table:start -->/ {
      print
      print "<!-- Generated by scripts/render-harness-docs.sh — do not edit -->"
      while ((getline line < content_file) > 0) {
        print line
      }
      close(content_file)
      in_block = 1
      next
    }
    /<!-- crossrev:harness-table:end -->/ {
      in_block = 0
      print
      next
    }
    !in_block { print }
  ' "$target"
}

any_diff=0

process_doc() {
  local rel_path="$1" render_fn="$2"
  local target="$REPO_ROOT/$rel_path"
  if [[ ! -f "$target" ]]; then
    printf 'render-harness-docs: %s not found\n' "$target" >&2
    return 1
  fi

  local tmp_content tmp_out
  tmp_content="$(mktemp)"
  tmp_out="$(mktemp)"

  "$render_fn" >"$tmp_content"
  replace_table "$target" "$tmp_content" >"$tmp_out"

  if (( check_mode )); then
    if ! diff -u "$target" "$tmp_out"; then
      any_diff=1
    fi
    rm -f "$tmp_content" "$tmp_out"
  else
    cat "$tmp_out" >"$target"
    rm -f "$tmp_content" "$tmp_out"
  fi
}

process_doc "README.md" render_readme
process_doc "docs/credentials.md" render_credentials
process_doc "docs/architecture.md" render_architecture

if (( check_mode && any_diff )); then
  exit 1
fi
