package intel_test

import (
	"context"
	"strings"
	"testing"

	"github.com/carlosboeing/crossrev/internal/core"
	"github.com/carlosboeing/crossrev/internal/intel"
)

// lockfileNames mirrors the design's fixed list: Linguist's lockfiles plus
// the common ones Linguist leaves out.
var lockfileNames = []string{
	"package-lock.json",
	"npm-shrinkwrap.json",
	"yarn.lock",
	"pnpm-lock.yaml",
	"bun.lock",
	"bun.lockb",
	"deno.lock",
	"Cargo.lock",
	"go.sum",
	"Gemfile.lock",
	"composer.lock",
	"poetry.lock",
	"pdm.lock",
	"uv.lock",
	"Pipfile.lock",
	"Package.resolved",
	"Podfile.lock",
	"pubspec.lock",
	"mix.lock",
	"packages.lock.json",
	"gradle.lockfile",
	"flake.lock",
	"MODULE.bazel.lock",
	".terraform.lock.hcl",
	"pixi.lock",
	"mise.lock",
}

func TestGeneratedSignalLockfiles(t *testing.T) {
	for _, name := range lockfileNames {
		t.Run(name, func(t *testing.T) {
			if got := intel.GeneratedSignal(name, nil); got != intel.SignalLockfile {
				t.Errorf("GeneratedSignal(%q, nil) = %q, want %q", name, got, intel.SignalLockfile)
			}
			nested := "sub/dir/" + name
			if got := intel.GeneratedSignal(nested, nil); got != intel.SignalLockfile {
				t.Errorf("GeneratedSignal(%q, nil) = %q, want %q (basename match)", nested, got, intel.SignalLockfile)
			}
		})
	}
}

func TestGeneratedSignalLockfileCaseAndExactness(t *testing.T) {
	negatives := []string{
		"PACKAGE-LOCK.JSON",
		"Package-lock.json",
		"Yarn.lock",
		"YARN.LOCK",
		"package.resolved", // the real name is Package.resolved
		"go.SUM",
		"cargo.lock",
		"package-lock.json.bak",
		"my-yarn.lock",
		"yarn.lock.txt",
		"dir/yarn.lock.old",
	}
	for _, name := range negatives {
		if got := intel.GeneratedSignal(name, nil); got != "" {
			t.Errorf("GeneratedSignal(%q, nil) = %q, want empty (exact case-sensitive basename)", name, got)
		}
	}
}

func TestGeneratedSignalBundleNames(t *testing.T) {
	positives := []string{
		"app.min.js",
		"app.min.css",
		"dist/app.min.js",
		"dist/app.min.css",
		"app.js.map",
		"app.css.map",
		"dist/app.js.map",
		"dist/app.css.map",
	}
	for _, name := range positives {
		if got := intel.GeneratedSignal(name, nil); got != intel.SignalBundleName {
			t.Errorf("GeneratedSignal(%q, nil) = %q, want %q", name, got, intel.SignalBundleName)
		}
	}
	negatives := []string{
		"app.min.ts",
		"app.js",
		"app.css",
		"app.map",
		"app.jsx.map",
		"app.min.js.bak",
	}
	for _, name := range negatives {
		if got := intel.GeneratedSignal(name, nil); got != "" {
			t.Errorf("GeneratedSignal(%q, nil) = %q, want empty", name, got)
		}
	}
}

func TestGeneratedSignalNameRulesBeatContentRules(t *testing.T) {
	header := []byte("// @generated by tool\n")
	if got := intel.GeneratedSignal("yarn.lock", header); got != intel.SignalLockfile {
		t.Errorf("lockfile with header = %q, want %q", got, intel.SignalLockfile)
	}
	if got := intel.GeneratedSignal("app.min.js", header); got != intel.SignalBundleName {
		t.Errorf("bundle name with header = %q, want %q", got, intel.SignalBundleName)
	}
	headerBeatsMinified := []byte("// @generated\n" + strings.Repeat("a", 200))
	if got := intel.GeneratedSignal("src/blob.ts", headerBeatsMinified); got != intel.SignalHeader {
		t.Errorf("header with minified body = %q, want %q", got, intel.SignalHeader)
	}
}

func TestGeneratedSignalHeaderForms(t *testing.T) {
	cases := []struct {
		name string
		body string
	}{
		{"go convention", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n"},
		{"go convention later line", "package x\n\n// Code generated by tool. DO NOT EDIT.\n"},
		{"at-generated token", "// @generated by tool\npackage x\n"},
		{"webAssets one-liner", "// generated by scripts/build-embed.mjs — do not edit\n"},
		{"two phrases separate lines", "package x\n// generated by tool\n\n\n\n\n// do not edit\n"},
		{"case ignored", "// GENERATED BY TOOL - DO NOT MODIFY\n"},
		{"autogenerated", "// autogenerated; do not edit\n"},
		{"auto-generated", "// auto-generated — do not modify\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := intel.GeneratedSignal("src/file.ts", []byte(c.body)); got != intel.SignalHeader {
				t.Errorf("GeneratedSignal = %q, want %q", got, intel.SignalHeader)
			}
		})
	}
}

func TestGeneratedSignalHeaderNegatives(t *testing.T) {
	cases := []struct {
		name string
		body string
	}{
		{"generated without do not edit", "// tests generated by hand\n"},
		{"do not edit without generated", "// do not edit this file\n"},
		{"do not modify without generated", "// please do not modify\n"},
		{"at-generated wrong case", "// @Generated by tool\n"},
		{"ordinary source", "package x\n\nfunc A() {}\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := intel.GeneratedSignal("src/file.go", []byte(c.body)); got != "" {
				t.Errorf("GeneratedSignal = %q, want empty", got)
			}
		})
	}
}

func TestGeneratedSignalHeaderWindow(t *testing.T) {
	marker := "// generated by tool — do not edit\n"
	// Marker on line 10 is inside the window; on line 11 it is not.
	tenLines := strings.Repeat("// filler\n", 9) + marker
	if got := intel.GeneratedSignal("src/file.ts", []byte(tenLines)); got != intel.SignalHeader {
		t.Errorf("marker on line 10 = %q, want %q", got, intel.SignalHeader)
	}
	elevenLines := strings.Repeat("// filler\n", 10) + marker
	if got := intel.GeneratedSignal("src/file.ts", []byte(elevenLines)); got != "" {
		t.Errorf("marker on line 11 = %q, want empty", got)
	}
	// A marker starting past byte 1024 is outside the window even on line 2.
	// The trailing NUL suppresses the minified rule, which the long filler
	// line would otherwise trip, so only the header window decides.
	longFirstLine := "// " + strings.Repeat("x", 1021) + "\n" + marker + "\x00"
	if len(longFirstLine) <= 1024 {
		t.Fatalf("fixture too short: %d bytes", len(longFirstLine))
	}
	if got := intel.GeneratedSignal("src/file.ts", []byte(longFirstLine)); got != "" {
		t.Errorf("marker past byte 1024 = %q, want empty", got)
	}
	// Without the NUL the same body matches the minified rule instead: the
	// byte window is no coverage hole for a long-line file.
	plain := strings.TrimRight(longFirstLine, "\x00")
	if got := intel.GeneratedSignal("src/file.ts", []byte(plain)); got != intel.SignalMinified {
		t.Errorf("marker past byte 1024 without NUL = %q, want %q", got, intel.SignalMinified)
	}
	// The two phrases split across the byte boundary do not match either.
	splitPhrases := "// generated " + strings.Repeat("x", 1012) + "\n// do not edit\n\x00"
	if len(splitPhrases) <= 1024 {
		t.Fatalf("fixture too short: %d bytes", len(splitPhrases))
	}
	if got := intel.GeneratedSignal("src/file.ts", []byte(splitPhrases)); got != "" {
		t.Errorf("phrases split across byte 1024 = %q, want empty", got)
	}
}

func TestGeneratedSignalMinifiedBoundaries(t *testing.T) {
	line110 := strings.Repeat("a", 110)
	line111 := strings.Repeat("a", 111)
	cases := []struct {
		name string
		path string
		body string
		want string
	}{
		{"empty body", "src/x.js", "", ""},
		{"no newline 110", "src/x.js", line110, ""},
		{"no newline 111", "src/x.js", line111, intel.SignalMinified},
		{"two lines averaging 110", "src/x.js", line110 + "\n" + strings.Repeat("b", 109), ""},
		{"two lines averaging 111", "src/x.js", line111 + "\n" + strings.Repeat("b", 110), intel.SignalMinified},
		{"trailing newline dilutes", "src/x.js", line111 + "\n", ""},
		{"ts extension", "src/webAssets.ts", line111, intel.SignalMinified},
		{"json extension", "data/openapi.json", line111, intel.SignalMinified},
		{"ordinary source", "src/x.go", "package x\n\nfunc A() {}\n", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := intel.GeneratedSignal(c.path, []byte(c.body)); got != c.want {
				t.Errorf("GeneratedSignal(%q) = %q, want %q", c.path, got, c.want)
			}
		})
	}
}

func TestGeneratedSignalBinaryBodies(t *testing.T) {
	longLine := strings.Repeat("a", 200)
	binary := []byte(longLine + "\n\x00" + longLine)
	if got := intel.GeneratedSignal("src/blob.dat", binary); got != "" {
		t.Errorf("binary long-line body = %q, want empty (minified suppressed)", got)
	}
	// A binary body may still match a name or header rule.
	if got := intel.GeneratedSignal("yarn.lock", binary); got != intel.SignalLockfile {
		t.Errorf("binary lockfile = %q, want %q", got, intel.SignalLockfile)
	}
	headerBinary := []byte("// @generated\n\x00" + longLine)
	if got := intel.GeneratedSignal("src/blob.ts", headerBinary); got != intel.SignalHeader {
		t.Errorf("binary header body = %q, want %q", got, intel.SignalHeader)
	}
}

// TestRequiredFilesRecordsGeneratedSignals proves discovery records the signal
// from the evidence bytes at ContentRevision: the base for a deletion, the
// head otherwise.
func TestRequiredFilesRecordsGeneratedSignals(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{
		{Path: "web/yarn.lock", OldPath: "web/yarn.lock", Kind: core.ChangeDeleted},
		{Path: "src/webAssets.ts", Kind: core.ChangeModified},
		{Path: "src/plain.ts", Kind: core.ChangeModified},
	}
	reader := stubReader{bodies: map[string]map[string]oracleCase{
		stubBaseSHA: {
			"web/yarn.lock": {Path: "web/yarn.lock", Body: "# yarn lockfile v1\n", Available: true},
		},
		stubHeadSHA: {
			"src/webAssets.ts": {Path: "src/webAssets.ts", Body: "// generated by scripts/build-embed.mjs — do not edit\n", Available: true},
			"src/plain.ts":     {Path: "src/plain.ts", Body: "export const x = 1\n", Available: true},
		},
	}}
	scope, err := intel.RequiredFiles(context.Background(), changes, reader, base, head, nil, nil)
	if err != nil {
		t.Fatalf("RequiredFiles: %v", err)
	}
	want := map[string]string{
		"web/yarn.lock":    intel.SignalLockfile,
		"src/webAssets.ts": intel.SignalHeader,
		"src/plain.ts":     "",
	}
	if len(scope.Required) != len(want) {
		t.Fatalf("required holds %d units, want %d", len(scope.Required), len(want))
	}
	for _, unit := range scope.Required {
		if unit.Generated != want[unit.Path] {
			t.Errorf("unit %q Generated = %q, want %q", unit.Path, unit.Generated, want[unit.Path])
		}
	}
}

// TestRequiredFilesLeavesUnreadableBodyUnsigned proves an unreadable body
// stays required without a content-based signal.
func TestRequiredFilesLeavesUnreadableBodyUnsigned(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{{Path: "src/locked.go", Kind: core.ChangeModified}}
	scope, err := intel.RequiredFiles(context.Background(), changes, failingReader{}, base, head, nil, nil)
	if err != nil {
		t.Fatalf("RequiredFiles: %v", err)
	}
	if len(scope.Required) != 1 {
		t.Fatalf("required holds %d units, want 1", len(scope.Required))
	}
	unit := scope.Required[0]
	if unit.Available {
		t.Error("unreadable unit reports available")
	}
	if unit.Generated != "" {
		t.Errorf("unreadable unit Generated = %q, want empty", unit.Generated)
	}
}

func TestClassifyGenerated(t *testing.T) {
	cases := []struct {
		name   string
		attr   intel.AttributeDecision
		signal string
		source string
		rule   string
		effect intel.ClassEffect
	}{
		{"set excludes outright", intel.AttributeSet, "", intel.SourceGitattributes, "linguist-generated", intel.EffectExcluded},
		{"set ignores a built-in signal", intel.AttributeSet, intel.SignalHeader, intel.SourceGitattributes, "linguist-generated", intel.EffectExcluded},
		{"negated suppresses a built-in signal", intel.AttributeNegated, intel.SignalHeader, intel.SourceGitattributes, "linguist-generated", intel.EffectPlain},
		{"negated plain stays plain", intel.AttributeNegated, "", intel.SourceGitattributes, "linguist-generated", intel.EffectPlain},
		{"unspecified lets a signal speak", intel.AttributeUnspecified, intel.SignalLockfile, intel.SourceBuiltin, intel.SignalLockfile, intel.EffectGenerated},
		{"unspecified without a signal is plain", intel.AttributeUnspecified, "", "", "", intel.EffectPlain},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := intel.ClassifyGenerated(c.attr, c.signal)
			if got.Source != c.source || got.Rule != c.rule || got.Effect != c.effect {
				t.Errorf("ClassifyGenerated(%v, %q) = {%q %q %v}, want {%q %q %v}",
					c.attr, c.signal, got.Source, got.Rule, got.Effect, c.source, c.rule, c.effect)
			}
		})
	}
}

// recordingReader fails the test when the excluded path's body is asked for:
// repository policy excludes before any evidence is read.
type recordingReader struct {
	t       *testing.T
	bodies  map[string]string
	refused map[string]bool
}

func (r recordingReader) Read(_ context.Context, _ core.Revision, path string) (intel.FileBody, error) {
	if r.refused[path] {
		r.t.Errorf("body of policy-excluded %s was read", path)
		return intel.FileBody{Unavailable: true, Reason: "refused"}, nil
	}
	body, ok := r.bodies[path]
	if !ok {
		return intel.FileBody{Unavailable: true, Reason: "no such path"}, nil
	}
	return intel.FileBody{Data: []byte(body)}, nil
}

func TestRequiredFilesExcludesAttributeSetPathsBeforeReading(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{
		{Path: "dist/bundle.js", Kind: core.ChangeModified},
		{Path: "src/keep.go", Kind: core.ChangeModified},
	}
	reader := recordingReader{
		t:       t,
		bodies:  map[string]string{"src/keep.go": "package keep\n"},
		refused: map[string]bool{"dist/bundle.js": true},
	}
	attrs := map[string]intel.AttributeDecision{"dist/bundle.js": intel.AttributeSet}
	scope, err := intel.RequiredFiles(context.Background(), changes, reader, base, head, nil, attrs)
	if err != nil {
		t.Fatalf("RequiredFiles: %v", err)
	}
	if len(scope.Required) != 1 || scope.Required[0].Path != "src/keep.go" {
		t.Fatalf("required = %v, want only src/keep.go", scope.Required)
	}
	if len(scope.Excluded) != 1 {
		t.Fatalf("excluded = %v, want the marked path", scope.Excluded)
	}
	exclusion := scope.Excluded[0]
	if exclusion.Path != "dist/bundle.js" {
		t.Errorf("excluded path = %q, want dist/bundle.js", exclusion.Path)
	}
	if exclusion.Reason != "generated: linguist-generated in .gitattributes" {
		t.Errorf("exclusion reason = %q", exclusion.Reason)
	}
}

// An oversized header-marked file under -linguist-generated carries no
// generated signal: the attribute suppresses every built-in rule, so the
// file is reviewed when it fits and halts when it does not.
func TestRequiredFilesNegatedSuppressesTheBuiltInSignal(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{{Path: "src/webAssets.ts", Kind: core.ChangeModified}}
	reader := stubReader{bodies: map[string]map[string]oracleCase{
		stubBaseSHA: {},
		stubHeadSHA: {
			"src/webAssets.ts": {Path: "src/webAssets.ts", Body: "// generated by scripts/build-embed.mjs — do not edit\n", Available: true},
		},
	}}
	attrs := map[string]intel.AttributeDecision{"src/webAssets.ts": intel.AttributeNegated}
	scope, err := intel.RequiredFiles(context.Background(), changes, reader, base, head, nil, attrs)
	if err != nil {
		t.Fatalf("RequiredFiles: %v", err)
	}
	if len(scope.Required) != 1 {
		t.Fatalf("required holds %d units, want 1", len(scope.Required))
	}
	unit := scope.Required[0]
	if !unit.Available {
		t.Fatal("the negated unit was not read")
	}
	if unit.Generated != "" {
		t.Errorf("Generated = %q, want empty under -linguist-generated", unit.Generated)
	}
	if len(scope.Excluded) != 0 {
		t.Errorf("excluded = %v, want none", scope.Excluded)
	}
}

// The attribute answer keys on the current path only: a rename out of a
// marked directory is a new review obligation, and a mark on the old path
// does not follow the file.
func TestRequiredFilesAttributesKeyOnTheCurrentPath(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{
		{OldPath: "dist/old.go", Path: "src/new.go", Kind: core.ChangeRenamed},
	}
	reader := stubReader{bodies: map[string]map[string]oracleCase{
		stubBaseSHA: {},
		stubHeadSHA: {"src/new.go": {Path: "src/new.go", Body: "package src\n", Available: true}},
	}}

	t.Run("a mark on the old path does not follow", func(t *testing.T) {
		attrs := map[string]intel.AttributeDecision{"dist/old.go": intel.AttributeSet}
		scope, err := intel.RequiredFiles(context.Background(), changes, reader, base, head, nil, attrs)
		if err != nil {
			t.Fatalf("RequiredFiles: %v", err)
		}
		if len(scope.Required) != 1 || len(scope.Excluded) != 0 {
			t.Fatalf("required = %v excluded = %v, want the renamed file required", scope.Required, scope.Excluded)
		}
	})

	t.Run("a mark on the current path excludes", func(t *testing.T) {
		attrs := map[string]intel.AttributeDecision{"src/new.go": intel.AttributeSet}
		scope, err := intel.RequiredFiles(context.Background(), changes, reader, base, head, nil, attrs)
		if err != nil {
			t.Fatalf("RequiredFiles: %v", err)
		}
		if len(scope.Required) != 0 || len(scope.Excluded) != 1 {
			t.Fatalf("required = %v excluded = %v, want the renamed file excluded", scope.Required, scope.Excluded)
		}
	})
}

// The backlog rule keeps its old-or-new-path match beside the attribute
// read: a rename out of the backlog stays excluded.
func TestRequiredFilesBacklogMatchSurvivesAttributes(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{
		{OldPath: "docs/backlog/item.md", Path: "docs/elsewhere/item.md", Kind: core.ChangeRenamed},
		{Path: "src/keep.go", Kind: core.ChangeModified},
	}
	reader := stubReader{bodies: map[string]map[string]oracleCase{
		stubBaseSHA: {},
		stubHeadSHA: {"src/keep.go": {Path: "src/keep.go", Body: "package keep\n", Available: true}},
	}}
	excluded := []intel.Exclusion{{Path: "docs/backlog", Reason: "backlog destination"}}
	attrs := map[string]intel.AttributeDecision{"docs/elsewhere/item.md": intel.AttributeUnspecified}
	scope, err := intel.RequiredFiles(context.Background(), changes, reader, base, head, excluded, attrs)
	if err != nil {
		t.Fatalf("RequiredFiles: %v", err)
	}
	if len(scope.Required) != 1 || scope.Required[0].Path != "src/keep.go" {
		t.Fatalf("required = %v, want only src/keep.go", scope.Required)
	}
	if len(scope.Excluded) != 1 || scope.Excluded[0].Reason != "backlog destination" {
		t.Fatalf("excluded = %v, want the backlog path with its reason", scope.Excluded)
	}
}

// The header excerpt quotes the matched marker line for the PR warning. It
// is derived from the same bounded window the detector read, sanitized of
// backticks and control bytes, and capped at 120 bytes with an ellipsis — a
// marker can sit on a minified line of any length.
func TestHeaderExcerpt(t *testing.T) {
	t.Run("the marker line itself", func(t *testing.T) {
		body := "// generated by scripts/build-embed.mjs — do not edit\n" + strings.Repeat("a", 1000) + "\n"
		if got := intel.HeaderExcerpt([]byte(body)); got != "// generated by scripts/build-embed.mjs — do not edit" {
			t.Errorf("excerpt = %q", got)
		}
	})

	t.Run("a 300 KB line with backticks is sanitized and capped", func(t *testing.T) {
		line := "// generated by `build-embed` — do not edit " + strings.Repeat("a", 300*1024)
		got := intel.HeaderExcerpt([]byte(line))
		if len(got) > 120 {
			t.Errorf("excerpt is %d bytes, want at most 120", len(got))
		}
		if !strings.HasSuffix(got, "…") {
			t.Errorf("excerpt = %q, want a trailing ellipsis", got)
		}
		if strings.Contains(got, "`") {
			t.Errorf("excerpt kept a backtick: %q", got)
		}
		if !strings.HasPrefix(got, "// generated by build-embed") {
			t.Errorf("excerpt lost the marker text: %q", got)
		}
	})

	t.Run("control bytes are removed", func(t *testing.T) {
		body := "// Code generated by tool. DO NOT EDIT.\x07\x00\npackage x\n"
		got := intel.HeaderExcerpt([]byte(body))
		if got != "// Code generated by tool. DO NOT EDIT." {
			t.Errorf("excerpt = %q, want the control bytes gone", got)
		}
	})

	t.Run("the first marker line wins when the phrases split", func(t *testing.T) {
		body := "package x\n// generated by tool\n\n// do not edit\n"
		if got := intel.HeaderExcerpt([]byte(body)); got != "// generated by tool" {
			t.Errorf("excerpt = %q", got)
		}
	})

	t.Run("no marker no excerpt", func(t *testing.T) {
		if got := intel.HeaderExcerpt([]byte("package x\n")); got != "" {
			t.Errorf("excerpt = %q, want empty", got)
		}
	})

	t.Run("a marker past the window has no excerpt", func(t *testing.T) {
		body := strings.Repeat("// filler\n", 10) + "// generated by tool — do not edit\n"
		if got := intel.HeaderExcerpt([]byte(body)); got != "" {
			t.Errorf("excerpt = %q, want empty", got)
		}
	})
}
