package intel_test

import (
	"context"
	"strings"
	"testing"

	"github.com/carlosboeing/crossrev/internal/core"
	"github.com/carlosboeing/crossrev/internal/intel"
)

// lockfileNames mirrors the design's fixed list: Linguist's lockfiles plus
// the common ones Linguist leaves out.
var lockfileNames = []string{
	"package-lock.json",
	"npm-shrinkwrap.json",
	"yarn.lock",
	"pnpm-lock.yaml",
	"bun.lock",
	"bun.lockb",
	"deno.lock",
	"Cargo.lock",
	"go.sum",
	"Gemfile.lock",
	"composer.lock",
	"poetry.lock",
	"pdm.lock",
	"uv.lock",
	"Pipfile.lock",
	"Package.resolved",
	"Podfile.lock",
	"pubspec.lock",
	"mix.lock",
	"packages.lock.json",
	"gradle.lockfile",
	"flake.lock",
	"MODULE.bazel.lock",
	".terraform.lock.hcl",
	"pixi.lock",
	"mise.lock",
}

func TestGeneratedSignalLockfiles(t *testing.T) {
	for _, name := range lockfileNames {
		t.Run(name, func(t *testing.T) {
			if got := intel.GeneratedSignal(name, nil); got != intel.SignalLockfile {
				t.Errorf("GeneratedSignal(%q, nil) = %q, want %q", name, got, intel.SignalLockfile)
			}
			nested := "sub/dir/" + name
			if got := intel.GeneratedSignal(nested, nil); got != intel.SignalLockfile {
				t.Errorf("GeneratedSignal(%q, nil) = %q, want %q (basename match)", nested, got, intel.SignalLockfile)
			}
		})
	}
}

func TestGeneratedSignalLockfileCaseAndExactness(t *testing.T) {
	negatives := []string{
		"PACKAGE-LOCK.JSON",
		"Package-lock.json",
		"Yarn.lock",
		"YARN.LOCK",
		"package.resolved", // the real name is Package.resolved
		"go.SUM",
		"cargo.lock",
		"package-lock.json.bak",
		"my-yarn.lock",
		"yarn.lock.txt",
		"dir/yarn.lock.old",
	}
	for _, name := range negatives {
		if got := intel.GeneratedSignal(name, nil); got != "" {
			t.Errorf("GeneratedSignal(%q, nil) = %q, want empty (exact case-sensitive basename)", name, got)
		}
	}
}

func TestGeneratedSignalBundleNames(t *testing.T) {
	positives := []string{
		"app.min.js",
		"app.min.css",
		"dist/app.min.js",
		"dist/app.min.css",
		"app.js.map",
		"app.css.map",
		"dist/app.js.map",
		"dist/app.css.map",
	}
	for _, name := range positives {
		if got := intel.GeneratedSignal(name, nil); got != intel.SignalBundleName {
			t.Errorf("GeneratedSignal(%q, nil) = %q, want %q", name, got, intel.SignalBundleName)
		}
	}
	negatives := []string{
		"app.min.ts",
		"app.js",
		"app.css",
		"app.map",
		"app.jsx.map",
		"app.min.js.bak",
	}
	for _, name := range negatives {
		if got := intel.GeneratedSignal(name, nil); got != "" {
			t.Errorf("GeneratedSignal(%q, nil) = %q, want empty", name, got)
		}
	}
}

func TestGeneratedSignalNameRulesBeatContentRules(t *testing.T) {
	header := []byte("// @generated by tool\n")
	if got := intel.GeneratedSignal("yarn.lock", header); got != intel.SignalLockfile {
		t.Errorf("lockfile with header = %q, want %q", got, intel.SignalLockfile)
	}
	if got := intel.GeneratedSignal("app.min.js", header); got != intel.SignalBundleName {
		t.Errorf("bundle name with header = %q, want %q", got, intel.SignalBundleName)
	}
	headerBeatsMinified := []byte("// @generated\n" + strings.Repeat("a", 200))
	if got := intel.GeneratedSignal("src/blob.ts", headerBeatsMinified); got != intel.SignalHeader {
		t.Errorf("header with minified body = %q, want %q", got, intel.SignalHeader)
	}
}

func TestGeneratedSignalHeaderForms(t *testing.T) {
	cases := []struct {
		name string
		body string
	}{
		{"go convention", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n"},
		{"go convention later line", "package x\n\n// Code generated by tool. DO NOT EDIT.\n"},
		{"at-generated token", "// @generated by tool\npackage x\n"},
		{"webAssets one-liner", "// generated by scripts/build-embed.mjs — do not edit\n"},
		{"two phrases separate lines", "package x\n// generated by tool\n\n\n\n\n// do not edit\n"},
		{"case ignored", "// GENERATED BY TOOL - DO NOT MODIFY\n"},
		{"autogenerated", "// autogenerated; do not edit\n"},
		{"auto-generated", "// auto-generated — do not modify\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := intel.GeneratedSignal("src/file.ts", []byte(c.body)); got != intel.SignalHeader {
				t.Errorf("GeneratedSignal = %q, want %q", got, intel.SignalHeader)
			}
		})
	}
}

func TestGeneratedSignalHeaderNegatives(t *testing.T) {
	cases := []struct {
		name string
		body string
	}{
		{"generated without do not edit", "// tests generated by hand\n"},
		{"do not edit without generated", "// do not edit this file\n"},
		{"do not modify without generated", "// please do not modify\n"},
		{"at-generated wrong case", "// @Generated by tool\n"},
		{"ordinary source", "package x\n\nfunc A() {}\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := intel.GeneratedSignal("src/file.go", []byte(c.body)); got != "" {
				t.Errorf("GeneratedSignal = %q, want empty", got)
			}
		})
	}
}

func TestGeneratedSignalHeaderWindow(t *testing.T) {
	marker := "// generated by tool — do not edit\n"
	// Marker on line 10 is inside the window; on line 11 it is not.
	tenLines := strings.Repeat("// filler\n", 9) + marker
	if got := intel.GeneratedSignal("src/file.ts", []byte(tenLines)); got != intel.SignalHeader {
		t.Errorf("marker on line 10 = %q, want %q", got, intel.SignalHeader)
	}
	elevenLines := strings.Repeat("// filler\n", 10) + marker
	if got := intel.GeneratedSignal("src/file.ts", []byte(elevenLines)); got != "" {
		t.Errorf("marker on line 11 = %q, want empty", got)
	}
	// A marker starting past byte 1024 is outside the window even on line 2.
	// The trailing NUL suppresses the minified rule, which the long filler
	// line would otherwise trip, so only the header window decides.
	longFirstLine := "// " + strings.Repeat("x", 1021) + "\n" + marker + "\x00"
	if len(longFirstLine) <= 1024 {
		t.Fatalf("fixture too short: %d bytes", len(longFirstLine))
	}
	if got := intel.GeneratedSignal("src/file.ts", []byte(longFirstLine)); got != "" {
		t.Errorf("marker past byte 1024 = %q, want empty", got)
	}
	// Without the NUL the same body matches the minified rule instead: the
	// byte window is no coverage hole for a long-line file.
	plain := strings.TrimRight(longFirstLine, "\x00")
	if got := intel.GeneratedSignal("src/file.ts", []byte(plain)); got != intel.SignalMinified {
		t.Errorf("marker past byte 1024 without NUL = %q, want %q", got, intel.SignalMinified)
	}
	// The two phrases split across the byte boundary do not match either.
	splitPhrases := "// generated " + strings.Repeat("x", 1012) + "\n// do not edit\n\x00"
	if len(splitPhrases) <= 1024 {
		t.Fatalf("fixture too short: %d bytes", len(splitPhrases))
	}
	if got := intel.GeneratedSignal("src/file.ts", []byte(splitPhrases)); got != "" {
		t.Errorf("phrases split across byte 1024 = %q, want empty", got)
	}
}

func TestGeneratedSignalMinifiedBoundaries(t *testing.T) {
	line110 := strings.Repeat("a", 110)
	line111 := strings.Repeat("a", 111)
	cases := []struct {
		name string
		path string
		body string
		want string
	}{
		{"empty body", "src/x.js", "", ""},
		{"no newline 110", "src/x.js", line110, ""},
		{"no newline 111", "src/x.js", line111, intel.SignalMinified},
		{"two lines averaging 110", "src/x.js", line110 + "\n" + strings.Repeat("b", 109), ""},
		{"two lines averaging 111", "src/x.js", line111 + "\n" + strings.Repeat("b", 110), intel.SignalMinified},
		{"trailing newline dilutes", "src/x.js", line111 + "\n", ""},
		{"ts extension", "src/webAssets.ts", line111, intel.SignalMinified},
		{"json extension", "data/openapi.json", line111, intel.SignalMinified},
		{"ordinary source", "src/x.go", "package x\n\nfunc A() {}\n", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := intel.GeneratedSignal(c.path, []byte(c.body)); got != c.want {
				t.Errorf("GeneratedSignal(%q) = %q, want %q", c.path, got, c.want)
			}
		})
	}
}

func TestGeneratedSignalBinaryBodies(t *testing.T) {
	longLine := strings.Repeat("a", 200)
	binary := []byte(longLine + "\n\x00" + longLine)
	if got := intel.GeneratedSignal("src/blob.dat", binary); got != "" {
		t.Errorf("binary long-line body = %q, want empty (minified suppressed)", got)
	}
	// A binary body may still match a name or header rule.
	if got := intel.GeneratedSignal("yarn.lock", binary); got != intel.SignalLockfile {
		t.Errorf("binary lockfile = %q, want %q", got, intel.SignalLockfile)
	}
	headerBinary := []byte("// @generated\n\x00" + longLine)
	if got := intel.GeneratedSignal("src/blob.ts", headerBinary); got != intel.SignalHeader {
		t.Errorf("binary header body = %q, want %q", got, intel.SignalHeader)
	}
}

// TestRequiredFilesRecordsGeneratedSignals proves discovery records the signal
// from the evidence bytes at ContentRevision: the base for a deletion, the
// head otherwise.
func TestRequiredFilesRecordsGeneratedSignals(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{
		{Path: "web/yarn.lock", OldPath: "web/yarn.lock", Kind: core.ChangeDeleted},
		{Path: "src/webAssets.ts", Kind: core.ChangeModified},
		{Path: "src/plain.ts", Kind: core.ChangeModified},
	}
	reader := stubReader{bodies: map[string]map[string]oracleCase{
		stubBaseSHA: {
			"web/yarn.lock": {Path: "web/yarn.lock", Body: "# yarn lockfile v1\n", Available: true},
		},
		stubHeadSHA: {
			"src/webAssets.ts": {Path: "src/webAssets.ts", Body: "// generated by scripts/build-embed.mjs — do not edit\n", Available: true},
			"src/plain.ts":     {Path: "src/plain.ts", Body: "export const x = 1\n", Available: true},
		},
	}}
	scope, err := intel.RequiredFiles(context.Background(), changes, reader, base, head, nil)
	if err != nil {
		t.Fatalf("RequiredFiles: %v", err)
	}
	want := map[string]string{
		"web/yarn.lock":    intel.SignalLockfile,
		"src/webAssets.ts": intel.SignalHeader,
		"src/plain.ts":     "",
	}
	if len(scope.Required) != len(want) {
		t.Fatalf("required holds %d units, want %d", len(scope.Required), len(want))
	}
	for _, unit := range scope.Required {
		if unit.Generated != want[unit.Path] {
			t.Errorf("unit %q Generated = %q, want %q", unit.Path, unit.Generated, want[unit.Path])
		}
	}
}

// TestRequiredFilesLeavesUnreadableBodyUnsigned proves an unreadable body
// stays required without a content-based signal.
func TestRequiredFilesLeavesUnreadableBodyUnsigned(t *testing.T) {
	base, head := stubRevisions(t)
	changes := []core.FileChange{{Path: "src/locked.go", Kind: core.ChangeModified}}
	scope, err := intel.RequiredFiles(context.Background(), changes, failingReader{}, base, head, nil)
	if err != nil {
		t.Fatalf("RequiredFiles: %v", err)
	}
	if len(scope.Required) != 1 {
		t.Fatalf("required holds %d units, want 1", len(scope.Required))
	}
	unit := scope.Required[0]
	if unit.Available {
		t.Error("unreadable unit reports available")
	}
	if unit.Generated != "" {
		t.Errorf("unreadable unit Generated = %q, want empty", unit.Generated)
	}
}
